export const structuredData = {
  CaseInformation: {
    Date: "03/10/2025",
    MedicalID: "201596",
    ParentName: "Amanda Teffe",
    HospitalName: "UUTH",
    InterviewerName: "Amanda Teffe",
    DateOfAdmission: "02/10/2025",
    ApproximateTimeOfAdmission: "11:50 AM",
    ChildsAgeInMonths: "16",
    ChildsDateOfBirth: "14/10/2023",
    ChildsSex: "Female",
    ChildsCurrentWeight: "5.2 kg",
    ChildsCurrentHeight: "70 cm",
    ChildsMidArmCircumference: "13 cm",
  },
  ClinicalHistory: {
    DateOfSymptomOnset: "02/10/2025",
    Diarrhea: "Yes",
    ChronicPersistentDiarrhea: "No",
    DiarrheaDuration: "2 days",
    DiarrheaEpisodes: "5 episodes",
    BloodInStool: "No",
    Vomiting: "Yes",
    VomitingDuration: ">1 day",
    VomitingEpisodes: ">22 episodes",
    OralRehydrationSolution: "Yes",
    GeneralCondition: "Restless, irritable",
    SunkenEyes: "Yes",
    FirstStatus: "Drink normally, no thirsty",
    SkinPinch: "Gets back slowly (1-2 seconds)",
    LevelOfDehydration: "Severe",
    IVFluids: "Yes",
    OralRehydrationTherapy: "Yes",
    HistoryOfFever: "Yes",
    HighestTemperature: "39.8°C",
    ChronicMedicalConditions: "No",
  },
};
